AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Globals:
  Function:
    Runtime: nodejs18.x

Resources:
  RegistPdfFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: ../dist/
      Handler: handlers/pdf/registPdf.handler
      Role: arn:aws:iam::224372234572:role/aiseeker-dev
      Timeout: 60
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /api/pdf
            Method: post

  DeletePdfFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: ../dist/
      Handler: handlers/pdf/deletePdf.handler
      Role: arn:aws:iam::224372234572:role/aiseeker-dev
      Timeout: 60
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /api/pdf
            Method: delete

  SendQueryFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: ../dist/
      Handler: handlers/query/sendQuery.handler
      Role: arn:aws:iam::224372234572:role/aiseeker-dev
      Timeout: 120
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /api/query
            Method: post

  PingFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: ../dist/
      Handler: handlers/ping.handler
      Role: arn:aws:iam::224372234572:role/aiseeker-dev
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /api/ping
            Method: get